addressbook {"data":{
    "containerUrl":"https://sstratsianis.solidcommunity.net/contacts/",
        "dataset":{
        "type":"Dataset",
            "graphs":{
            "default":{
                "https://inrupt.com/.well-known/sdk-local-node/this":{
                    "type":"Subject",
                        "predicates":{
                        "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":{
                            "namedNodes":["http://www.w3.org/2006/vcard/ns#AddressBook"]},
                        "http://www.w3.org/ns/auth/acl#owner":{
                            "namedNodes":
                            ["https://sstratsianis.solidcommunity.net/profile/card#me"]},
                        "http://purl.org/dc/elements/1.1/title":{
                            "literals":{"http://www.w3.org/2001/XMLSchema#string":
                                ["Contacts"]}}},"url":"https://inrupt.com/.well-known/sdk-local-node/this"}}},
        "internal_changeLog":{"additions":[
            {"subject":{
                "value":"https://inrupt.com/.well-known/sdk-local-node/this"},
                "predicate":{"value":"http://www.w3.org/1999/02/22-rdf-syntax-ns#type"},
                "object":{"value":"http://www.w3.org/2006/vcard/ns#AddressBook"},
                "graph":{}},{"subject":{"value":"https://inrupt.com/.well-known/sdk-local-node/this"},
                "predicate":{"value":"http://www.w3.org/ns/auth/acl#owner"},
                "object":{"value":"https://sstratsianis.solidcommunity.net/profile/card#me"},
                "graph":{}},{"subject":{"value":"https://inrupt.com/.well-known/sdk-local-node/this"},
                "predicate":{"value":"http://purl.org/dc/elements/1.1/title"},
                "object":{"value":"Contacts","datatype":{"value":"http://www.w3.org/2001/XMLSchema#string"},
                    "language":""},"graph":{}}],"deletions":[]}},
    "thing":{"type":"Subject","predicates":{"http://www.w3.org/1999/02/22-rdf-syntax-ns#type":{"namedNodes":
        ["http://www.w3.org/2006/vcard/ns#AddressBook"]},"http://www.w3.org/ns/auth/acl#owner":
        {"namedNodes":["https://sstratsianis.solidcommunity.net/profile/card#me"]},
        "http://purl.org/dc/elements/1.1/title":{
        "literals":{"http://www.w3.org/2001/XMLSchema#string":
                ["Contacts"]}}},
        "url":"https://inrupt.com/.well-known/sdk-local-node/this"}},"isValidating":false}